// Package schemas provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package schemas

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerScopes = "bearer.Scopes"
)

// CreateGoodluckRequest defines model for CreateGoodluckRequest.
type CreateGoodluckRequest struct {
	TodoId *string `json:"todo_id,omitempty"`
	UserId *string `json:"user_id,omitempty"`
}

// CreateGoodluckResponse defines model for CreateGoodluckResponse.
type CreateGoodluckResponse struct {
	Message *string `json:"message,omitempty"`
}

// CreateTodoRequest defines model for CreateTodoRequest.
type CreateTodoRequest struct {
	Content     *string    `json:"content,omitempty"`
	DueDatetime *time.Time `json:"due_datetime,omitempty"`
	Status      *string    `json:"status,omitempty"`
	Title       *string    `json:"title,omitempty"`
}

// CreateTodoResponse defines model for CreateTodoResponse.
type CreateTodoResponse struct {
	Id *string `json:"id,omitempty"`
}

// DeleteGoodluckResponse defines model for DeleteGoodluckResponse.
type DeleteGoodluckResponse struct {
	Message *string `json:"message,omitempty"`
}

// DeleteTodoResponse defines model for DeleteTodoResponse.
type DeleteTodoResponse struct {
	Message *string `json:"message,omitempty"`
}

// GetTodoDetailResponse defines model for GetTodoDetailResponse.
type GetTodoDetailResponse struct {
	Content     *string    `json:"content,omitempty"`
	DueDatetime *time.Time `json:"due_datetime,omitempty"`
	Status      *string    `json:"status,omitempty"`
	Title       *string    `json:"title,omitempty"`
}

// GetTodoListResponse defines model for GetTodoListResponse.
type GetTodoListResponse = []struct {
	DueDatetime *time.Time `json:"due_datetime,omitempty"`
	Id          *string    `json:"id,omitempty"`
	Status      *string    `json:"status,omitempty"`
	Title       *string    `json:"title,omitempty"`
}

// GetUserDetailResponse defines model for GetUserDetailResponse.
type GetUserDetailResponse struct {
	Email    *openapi_types.Email `json:"email,omitempty"`
	Nickname *string              `json:"nickname,omitempty"`
}

// LoginUserRequest defines model for LoginUserRequest.
type LoginUserRequest struct {
	Email    *openapi_types.Email `json:"email,omitempty"`
	Password *string              `json:"password,omitempty"`
}

// LoginUserResponse defines model for LoginUserResponse.
type LoginUserResponse struct {
	AccessToken  *string `json:"access_token,omitempty"`
	RefreshToken *string `json:"refresh_token,omitempty"`
	Uid          *string `json:"uid,omitempty"`
}

// LogoutUserRequest defines model for LogoutUserRequest.
type LogoutUserRequest struct {
	UserId *string `json:"user_id,omitempty"`
}

// LogoutUserResponse defines model for LogoutUserResponse.
type LogoutUserResponse struct {
	Message *string `json:"message,omitempty"`
}

// RegisterUserRequest defines model for RegisterUserRequest.
type RegisterUserRequest struct {
	Email    *openapi_types.Email `json:"email,omitempty"`
	Nickname *string              `json:"nickname,omitempty"`
	Password *string              `json:"password,omitempty"`
}

// RegisterUserResponse defines model for RegisterUserResponse.
type RegisterUserResponse struct {
	AccessToken  *string `json:"access_token,omitempty"`
	RefreshToken *string `json:"refresh_token,omitempty"`
	Uid          *string `json:"uid,omitempty"`
}

// UpdateTodoRequest defines model for UpdateTodoRequest.
type UpdateTodoRequest struct {
	Content     *string    `json:"content,omitempty"`
	DueDatetime *time.Time `json:"due_datetime,omitempty"`
	Status      *string    `json:"status,omitempty"`
	Title       *string    `json:"title,omitempty"`
}

// UpdateTodoResponse defines model for UpdateTodoResponse.
type UpdateTodoResponse struct {
	Id *string `json:"id,omitempty"`
}

// UpdateUserRequest defines model for UpdateUserRequest.
type UpdateUserRequest struct {
	Email    *openapi_types.Email `json:"email,omitempty"`
	Nickname *string              `json:"nickname,omitempty"`
}

// UpdateUserResponse defines model for UpdateUserResponse.
type UpdateUserResponse struct {
	Email    *openapi_types.Email `json:"email,omitempty"`
	Nickname *string              `json:"nickname,omitempty"`
}

// TodoId defines model for todo_id.
type TodoId = string

// UserId defines model for user_id.
type UserId = string

// BadRequest defines model for BadRequest.
type BadRequest struct {
	Error *string `json:"error,omitempty"`
}

// Forbidden defines model for Forbidden.
type Forbidden struct {
	Error *string `json:"error,omitempty"`
}

// InternalServerError defines model for InternalServerError.
type InternalServerError struct {
	Error *string `json:"error,omitempty"`
}

// NotFound defines model for NotFound.
type NotFound struct {
	Error *string `json:"error,omitempty"`
}

// Unauthorized defines model for Unauthorized.
type Unauthorized struct {
	Error *string `json:"error,omitempty"`
}

// PostLoginJSONRequestBody defines body for PostLogin for application/json ContentType.
type PostLoginJSONRequestBody = LoginUserRequest

// PostLogoutJSONRequestBody defines body for PostLogout for application/json ContentType.
type PostLogoutJSONRequestBody = LogoutUserRequest

// PostRegisterJSONRequestBody defines body for PostRegister for application/json ContentType.
type PostRegisterJSONRequestBody = RegisterUserRequest

// PutUsersUserIdJSONRequestBody defines body for PutUsersUserId for application/json ContentType.
type PutUsersUserIdJSONRequestBody = UpdateUserRequest

// PostUsersUserIdTodosJSONRequestBody defines body for PostUsersUserIdTodos for application/json ContentType.
type PostUsersUserIdTodosJSONRequestBody = CreateTodoRequest

// PutUsersUserIdTodosTodoIdJSONRequestBody defines body for PutUsersUserIdTodosTodoId for application/json ContentType.
type PutUsersUserIdTodosTodoIdJSONRequestBody = UpdateTodoRequest

// PostUsersUserIdTodosTodoIdGoodlucksJSONRequestBody defines body for PostUsersUserIdTodosTodoIdGoodlucks for application/json ContentType.
type PostUsersUserIdTodosTodoIdGoodlucksJSONRequestBody = CreateGoodluckRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ログイン
	// (POST /login)
	PostLogin(c *gin.Context)
	// ログアウト
	// (POST /logout)
	PostLogout(c *gin.Context)
	// ユーザー登録
	// (POST /register)
	PostRegister(c *gin.Context)
	// ユーザー詳細取得
	// (GET /users/{user_id})
	GetUsersUserId(c *gin.Context, userId UserId)
	// ユーザー情報編集
	// (PUT /users/{user_id})
	PutUsersUserId(c *gin.Context, userId UserId)
	// Todo一覧取得
	// (GET /users/{user_id}/todos)
	GetUsersUserIdTodos(c *gin.Context, userId UserId)
	// Todo作成
	// (POST /users/{user_id}/todos)
	PostUsersUserIdTodos(c *gin.Context, userId UserId)
	// Todo削除
	// (DELETE /users/{user_id}/todos/{todo_id})
	DeleteUsersUserIdTodosTodoId(c *gin.Context, userId UserId, todoId TodoId)
	// Todo詳細取得
	// (GET /users/{user_id}/todos/{todo_id})
	GetUsersUserIdTodosTodoId(c *gin.Context, userId UserId, todoId TodoId)
	// Todo編集
	// (PUT /users/{user_id}/todos/{todo_id})
	PutUsersUserIdTodosTodoId(c *gin.Context, userId UserId, todoId TodoId)
	// いいね削除
	// (DELETE /users/{user_id}/todos/{todo_id}/goodlucks)
	DeleteUsersUserIdTodosTodoIdGoodlucks(c *gin.Context, userId UserId, todoId TodoId)
	// いいね作成
	// (POST /users/{user_id}/todos/{todo_id}/goodlucks)
	PostUsersUserIdTodosTodoIdGoodlucks(c *gin.Context, userId UserId, todoId TodoId)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// PostLogin operation middleware
func (siw *ServerInterfaceWrapper) PostLogin(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostLogin(c)
}

// PostLogout operation middleware
func (siw *ServerInterfaceWrapper) PostLogout(c *gin.Context) {

	c.Set(BearerScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostLogout(c)
}

// PostRegister operation middleware
func (siw *ServerInterfaceWrapper) PostRegister(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostRegister(c)
}

// GetUsersUserId operation middleware
func (siw *ServerInterfaceWrapper) GetUsersUserId(c *gin.Context) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", c.Param("user_id"), &userId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter user_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetUsersUserId(c, userId)
}

// PutUsersUserId operation middleware
func (siw *ServerInterfaceWrapper) PutUsersUserId(c *gin.Context) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", c.Param("user_id"), &userId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter user_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutUsersUserId(c, userId)
}

// GetUsersUserIdTodos operation middleware
func (siw *ServerInterfaceWrapper) GetUsersUserIdTodos(c *gin.Context) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", c.Param("user_id"), &userId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter user_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetUsersUserIdTodos(c, userId)
}

// PostUsersUserIdTodos operation middleware
func (siw *ServerInterfaceWrapper) PostUsersUserIdTodos(c *gin.Context) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", c.Param("user_id"), &userId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter user_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostUsersUserIdTodos(c, userId)
}

// DeleteUsersUserIdTodosTodoId operation middleware
func (siw *ServerInterfaceWrapper) DeleteUsersUserIdTodosTodoId(c *gin.Context) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", c.Param("user_id"), &userId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter user_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "todo_id" -------------
	var todoId TodoId

	err = runtime.BindStyledParameterWithOptions("simple", "todo_id", c.Param("todo_id"), &todoId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter todo_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteUsersUserIdTodosTodoId(c, userId, todoId)
}

// GetUsersUserIdTodosTodoId operation middleware
func (siw *ServerInterfaceWrapper) GetUsersUserIdTodosTodoId(c *gin.Context) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", c.Param("user_id"), &userId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter user_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "todo_id" -------------
	var todoId TodoId

	err = runtime.BindStyledParameterWithOptions("simple", "todo_id", c.Param("todo_id"), &todoId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter todo_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetUsersUserIdTodosTodoId(c, userId, todoId)
}

// PutUsersUserIdTodosTodoId operation middleware
func (siw *ServerInterfaceWrapper) PutUsersUserIdTodosTodoId(c *gin.Context) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", c.Param("user_id"), &userId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter user_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "todo_id" -------------
	var todoId TodoId

	err = runtime.BindStyledParameterWithOptions("simple", "todo_id", c.Param("todo_id"), &todoId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter todo_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutUsersUserIdTodosTodoId(c, userId, todoId)
}

// DeleteUsersUserIdTodosTodoIdGoodlucks operation middleware
func (siw *ServerInterfaceWrapper) DeleteUsersUserIdTodosTodoIdGoodlucks(c *gin.Context) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", c.Param("user_id"), &userId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter user_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "todo_id" -------------
	var todoId TodoId

	err = runtime.BindStyledParameterWithOptions("simple", "todo_id", c.Param("todo_id"), &todoId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter todo_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteUsersUserIdTodosTodoIdGoodlucks(c, userId, todoId)
}

// PostUsersUserIdTodosTodoIdGoodlucks operation middleware
func (siw *ServerInterfaceWrapper) PostUsersUserIdTodosTodoIdGoodlucks(c *gin.Context) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", c.Param("user_id"), &userId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter user_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "todo_id" -------------
	var todoId TodoId

	err = runtime.BindStyledParameterWithOptions("simple", "todo_id", c.Param("todo_id"), &todoId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter todo_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostUsersUserIdTodosTodoIdGoodlucks(c, userId, todoId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/login", wrapper.PostLogin)
	router.POST(options.BaseURL+"/logout", wrapper.PostLogout)
	router.POST(options.BaseURL+"/register", wrapper.PostRegister)
	router.GET(options.BaseURL+"/users/:user_id", wrapper.GetUsersUserId)
	router.PUT(options.BaseURL+"/users/:user_id", wrapper.PutUsersUserId)
	router.GET(options.BaseURL+"/users/:user_id/todos", wrapper.GetUsersUserIdTodos)
	router.POST(options.BaseURL+"/users/:user_id/todos", wrapper.PostUsersUserIdTodos)
	router.DELETE(options.BaseURL+"/users/:user_id/todos/:todo_id", wrapper.DeleteUsersUserIdTodosTodoId)
	router.GET(options.BaseURL+"/users/:user_id/todos/:todo_id", wrapper.GetUsersUserIdTodosTodoId)
	router.PUT(options.BaseURL+"/users/:user_id/todos/:todo_id", wrapper.PutUsersUserIdTodosTodoId)
	router.DELETE(options.BaseURL+"/users/:user_id/todos/:todo_id/goodlucks", wrapper.DeleteUsersUserIdTodosTodoIdGoodlucks)
	router.POST(options.BaseURL+"/users/:user_id/todos/:todo_id/goodlucks", wrapper.PostUsersUserIdTodosTodoIdGoodlucks)
}

type BadRequestJSONResponse struct {
	Error *string `json:"error,omitempty"`
}

type ForbiddenJSONResponse struct {
	Error *string `json:"error,omitempty"`
}

type InternalServerErrorJSONResponse struct {
	Error *string `json:"error,omitempty"`
}

type NotFoundJSONResponse struct {
	Error *string `json:"error,omitempty"`
}

type UnauthorizedJSONResponse struct {
	Error *string `json:"error,omitempty"`
}

type PostLoginRequestObject struct {
	Body *PostLoginJSONRequestBody
}

type PostLoginResponseObject interface {
	VisitPostLoginResponse(w http.ResponseWriter) error
}

type PostLogin200JSONResponse LoginUserResponse

func (response PostLogin200JSONResponse) VisitPostLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostLogin400JSONResponse struct{ BadRequestJSONResponse }

func (response PostLogin400JSONResponse) VisitPostLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostLogin500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response PostLogin500JSONResponse) VisitPostLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostLogoutRequestObject struct {
	Body *PostLogoutJSONRequestBody
}

type PostLogoutResponseObject interface {
	VisitPostLogoutResponse(w http.ResponseWriter) error
}

type PostLogout200JSONResponse LogoutUserResponse

func (response PostLogout200JSONResponse) VisitPostLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostLogout400JSONResponse struct{ BadRequestJSONResponse }

func (response PostLogout400JSONResponse) VisitPostLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostLogout401JSONResponse struct{ UnauthorizedJSONResponse }

func (response PostLogout401JSONResponse) VisitPostLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostLogout500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response PostLogout500JSONResponse) VisitPostLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostRegisterRequestObject struct {
	Body *PostRegisterJSONRequestBody
}

type PostRegisterResponseObject interface {
	VisitPostRegisterResponse(w http.ResponseWriter) error
}

type PostRegister200JSONResponse RegisterUserResponse

func (response PostRegister200JSONResponse) VisitPostRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostRegister400JSONResponse struct{ BadRequestJSONResponse }

func (response PostRegister400JSONResponse) VisitPostRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostRegister500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response PostRegister500JSONResponse) VisitPostRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetUsersUserIdRequestObject struct {
	UserId UserId `json:"user_id"`
}

type GetUsersUserIdResponseObject interface {
	VisitGetUsersUserIdResponse(w http.ResponseWriter) error
}

type GetUsersUserId200JSONResponse GetUserDetailResponse

func (response GetUsersUserId200JSONResponse) VisitGetUsersUserIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetUsersUserId400JSONResponse struct{ BadRequestJSONResponse }

func (response GetUsersUserId400JSONResponse) VisitGetUsersUserIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetUsersUserId401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetUsersUserId401JSONResponse) VisitGetUsersUserIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetUsersUserId403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetUsersUserId403JSONResponse) VisitGetUsersUserIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetUsersUserId404JSONResponse struct{ NotFoundJSONResponse }

func (response GetUsersUserId404JSONResponse) VisitGetUsersUserIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetUsersUserId500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetUsersUserId500JSONResponse) VisitGetUsersUserIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PutUsersUserIdRequestObject struct {
	UserId UserId `json:"user_id"`
	Body   *PutUsersUserIdJSONRequestBody
}

type PutUsersUserIdResponseObject interface {
	VisitPutUsersUserIdResponse(w http.ResponseWriter) error
}

type PutUsersUserId200JSONResponse UpdateUserResponse

func (response PutUsersUserId200JSONResponse) VisitPutUsersUserIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PutUsersUserId400JSONResponse struct{ BadRequestJSONResponse }

func (response PutUsersUserId400JSONResponse) VisitPutUsersUserIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PutUsersUserId401JSONResponse struct{ UnauthorizedJSONResponse }

func (response PutUsersUserId401JSONResponse) VisitPutUsersUserIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PutUsersUserId403JSONResponse struct{ ForbiddenJSONResponse }

func (response PutUsersUserId403JSONResponse) VisitPutUsersUserIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type PutUsersUserId404JSONResponse struct{ NotFoundJSONResponse }

func (response PutUsersUserId404JSONResponse) VisitPutUsersUserIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PutUsersUserId500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response PutUsersUserId500JSONResponse) VisitPutUsersUserIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetUsersUserIdTodosRequestObject struct {
	UserId UserId `json:"user_id"`
}

type GetUsersUserIdTodosResponseObject interface {
	VisitGetUsersUserIdTodosResponse(w http.ResponseWriter) error
}

type GetUsersUserIdTodos200JSONResponse GetTodoListResponse

func (response GetUsersUserIdTodos200JSONResponse) VisitGetUsersUserIdTodosResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetUsersUserIdTodos400JSONResponse struct{ BadRequestJSONResponse }

func (response GetUsersUserIdTodos400JSONResponse) VisitGetUsersUserIdTodosResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetUsersUserIdTodos401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetUsersUserIdTodos401JSONResponse) VisitGetUsersUserIdTodosResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetUsersUserIdTodos403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetUsersUserIdTodos403JSONResponse) VisitGetUsersUserIdTodosResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetUsersUserIdTodos404JSONResponse struct{ NotFoundJSONResponse }

func (response GetUsersUserIdTodos404JSONResponse) VisitGetUsersUserIdTodosResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetUsersUserIdTodos500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetUsersUserIdTodos500JSONResponse) VisitGetUsersUserIdTodosResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostUsersUserIdTodosRequestObject struct {
	UserId UserId `json:"user_id"`
	Body   *PostUsersUserIdTodosJSONRequestBody
}

type PostUsersUserIdTodosResponseObject interface {
	VisitPostUsersUserIdTodosResponse(w http.ResponseWriter) error
}

type PostUsersUserIdTodos200JSONResponse CreateTodoResponse

func (response PostUsersUserIdTodos200JSONResponse) VisitPostUsersUserIdTodosResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostUsersUserIdTodos400JSONResponse struct{ BadRequestJSONResponse }

func (response PostUsersUserIdTodos400JSONResponse) VisitPostUsersUserIdTodosResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostUsersUserIdTodos401JSONResponse struct{ UnauthorizedJSONResponse }

func (response PostUsersUserIdTodos401JSONResponse) VisitPostUsersUserIdTodosResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostUsersUserIdTodos403JSONResponse struct{ ForbiddenJSONResponse }

func (response PostUsersUserIdTodos403JSONResponse) VisitPostUsersUserIdTodosResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type PostUsersUserIdTodos404JSONResponse struct{ NotFoundJSONResponse }

func (response PostUsersUserIdTodos404JSONResponse) VisitPostUsersUserIdTodosResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PostUsersUserIdTodos500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response PostUsersUserIdTodos500JSONResponse) VisitPostUsersUserIdTodosResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteUsersUserIdTodosTodoIdRequestObject struct {
	UserId UserId `json:"user_id"`
	TodoId TodoId `json:"todo_id"`
}

type DeleteUsersUserIdTodosTodoIdResponseObject interface {
	VisitDeleteUsersUserIdTodosTodoIdResponse(w http.ResponseWriter) error
}

type DeleteUsersUserIdTodosTodoId200JSONResponse DeleteTodoResponse

func (response DeleteUsersUserIdTodosTodoId200JSONResponse) VisitDeleteUsersUserIdTodosTodoIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeleteUsersUserIdTodosTodoId400JSONResponse struct{ BadRequestJSONResponse }

func (response DeleteUsersUserIdTodosTodoId400JSONResponse) VisitDeleteUsersUserIdTodosTodoIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DeleteUsersUserIdTodosTodoId401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteUsersUserIdTodosTodoId401JSONResponse) VisitDeleteUsersUserIdTodosTodoIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteUsersUserIdTodosTodoId403JSONResponse struct{ ForbiddenJSONResponse }

func (response DeleteUsersUserIdTodosTodoId403JSONResponse) VisitDeleteUsersUserIdTodosTodoIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type DeleteUsersUserIdTodosTodoId404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteUsersUserIdTodosTodoId404JSONResponse) VisitDeleteUsersUserIdTodosTodoIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteUsersUserIdTodosTodoId500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response DeleteUsersUserIdTodosTodoId500JSONResponse) VisitDeleteUsersUserIdTodosTodoIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetUsersUserIdTodosTodoIdRequestObject struct {
	UserId UserId `json:"user_id"`
	TodoId TodoId `json:"todo_id"`
}

type GetUsersUserIdTodosTodoIdResponseObject interface {
	VisitGetUsersUserIdTodosTodoIdResponse(w http.ResponseWriter) error
}

type GetUsersUserIdTodosTodoId200JSONResponse GetTodoDetailResponse

func (response GetUsersUserIdTodosTodoId200JSONResponse) VisitGetUsersUserIdTodosTodoIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetUsersUserIdTodosTodoId400JSONResponse struct{ BadRequestJSONResponse }

func (response GetUsersUserIdTodosTodoId400JSONResponse) VisitGetUsersUserIdTodosTodoIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetUsersUserIdTodosTodoId401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetUsersUserIdTodosTodoId401JSONResponse) VisitGetUsersUserIdTodosTodoIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetUsersUserIdTodosTodoId403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetUsersUserIdTodosTodoId403JSONResponse) VisitGetUsersUserIdTodosTodoIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetUsersUserIdTodosTodoId404JSONResponse struct{ NotFoundJSONResponse }

func (response GetUsersUserIdTodosTodoId404JSONResponse) VisitGetUsersUserIdTodosTodoIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetUsersUserIdTodosTodoId500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetUsersUserIdTodosTodoId500JSONResponse) VisitGetUsersUserIdTodosTodoIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PutUsersUserIdTodosTodoIdRequestObject struct {
	UserId UserId `json:"user_id"`
	TodoId TodoId `json:"todo_id"`
	Body   *PutUsersUserIdTodosTodoIdJSONRequestBody
}

type PutUsersUserIdTodosTodoIdResponseObject interface {
	VisitPutUsersUserIdTodosTodoIdResponse(w http.ResponseWriter) error
}

type PutUsersUserIdTodosTodoId200JSONResponse UpdateTodoResponse

func (response PutUsersUserIdTodosTodoId200JSONResponse) VisitPutUsersUserIdTodosTodoIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PutUsersUserIdTodosTodoId400JSONResponse struct{ BadRequestJSONResponse }

func (response PutUsersUserIdTodosTodoId400JSONResponse) VisitPutUsersUserIdTodosTodoIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PutUsersUserIdTodosTodoId401JSONResponse struct{ UnauthorizedJSONResponse }

func (response PutUsersUserIdTodosTodoId401JSONResponse) VisitPutUsersUserIdTodosTodoIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PutUsersUserIdTodosTodoId403JSONResponse struct{ ForbiddenJSONResponse }

func (response PutUsersUserIdTodosTodoId403JSONResponse) VisitPutUsersUserIdTodosTodoIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type PutUsersUserIdTodosTodoId404JSONResponse struct{ NotFoundJSONResponse }

func (response PutUsersUserIdTodosTodoId404JSONResponse) VisitPutUsersUserIdTodosTodoIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PutUsersUserIdTodosTodoId500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response PutUsersUserIdTodosTodoId500JSONResponse) VisitPutUsersUserIdTodosTodoIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteUsersUserIdTodosTodoIdGoodlucksRequestObject struct {
	UserId UserId `json:"user_id"`
	TodoId TodoId `json:"todo_id"`
}

type DeleteUsersUserIdTodosTodoIdGoodlucksResponseObject interface {
	VisitDeleteUsersUserIdTodosTodoIdGoodlucksResponse(w http.ResponseWriter) error
}

type DeleteUsersUserIdTodosTodoIdGoodlucks200JSONResponse DeleteGoodluckResponse

func (response DeleteUsersUserIdTodosTodoIdGoodlucks200JSONResponse) VisitDeleteUsersUserIdTodosTodoIdGoodlucksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeleteUsersUserIdTodosTodoIdGoodlucks400JSONResponse struct{ BadRequestJSONResponse }

func (response DeleteUsersUserIdTodosTodoIdGoodlucks400JSONResponse) VisitDeleteUsersUserIdTodosTodoIdGoodlucksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DeleteUsersUserIdTodosTodoIdGoodlucks401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteUsersUserIdTodosTodoIdGoodlucks401JSONResponse) VisitDeleteUsersUserIdTodosTodoIdGoodlucksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteUsersUserIdTodosTodoIdGoodlucks403JSONResponse struct{ ForbiddenJSONResponse }

func (response DeleteUsersUserIdTodosTodoIdGoodlucks403JSONResponse) VisitDeleteUsersUserIdTodosTodoIdGoodlucksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type DeleteUsersUserIdTodosTodoIdGoodlucks404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteUsersUserIdTodosTodoIdGoodlucks404JSONResponse) VisitDeleteUsersUserIdTodosTodoIdGoodlucksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteUsersUserIdTodosTodoIdGoodlucks500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response DeleteUsersUserIdTodosTodoIdGoodlucks500JSONResponse) VisitDeleteUsersUserIdTodosTodoIdGoodlucksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostUsersUserIdTodosTodoIdGoodlucksRequestObject struct {
	UserId UserId `json:"user_id"`
	TodoId TodoId `json:"todo_id"`
	Body   *PostUsersUserIdTodosTodoIdGoodlucksJSONRequestBody
}

type PostUsersUserIdTodosTodoIdGoodlucksResponseObject interface {
	VisitPostUsersUserIdTodosTodoIdGoodlucksResponse(w http.ResponseWriter) error
}

type PostUsersUserIdTodosTodoIdGoodlucks200JSONResponse CreateGoodluckResponse

func (response PostUsersUserIdTodosTodoIdGoodlucks200JSONResponse) VisitPostUsersUserIdTodosTodoIdGoodlucksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostUsersUserIdTodosTodoIdGoodlucks400JSONResponse struct{ BadRequestJSONResponse }

func (response PostUsersUserIdTodosTodoIdGoodlucks400JSONResponse) VisitPostUsersUserIdTodosTodoIdGoodlucksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostUsersUserIdTodosTodoIdGoodlucks401JSONResponse struct{ UnauthorizedJSONResponse }

func (response PostUsersUserIdTodosTodoIdGoodlucks401JSONResponse) VisitPostUsersUserIdTodosTodoIdGoodlucksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostUsersUserIdTodosTodoIdGoodlucks403JSONResponse struct{ ForbiddenJSONResponse }

func (response PostUsersUserIdTodosTodoIdGoodlucks403JSONResponse) VisitPostUsersUserIdTodosTodoIdGoodlucksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type PostUsersUserIdTodosTodoIdGoodlucks404JSONResponse struct{ NotFoundJSONResponse }

func (response PostUsersUserIdTodosTodoIdGoodlucks404JSONResponse) VisitPostUsersUserIdTodosTodoIdGoodlucksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PostUsersUserIdTodosTodoIdGoodlucks500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response PostUsersUserIdTodosTodoIdGoodlucks500JSONResponse) VisitPostUsersUserIdTodosTodoIdGoodlucksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ログイン
	// (POST /login)
	PostLogin(ctx context.Context, request PostLoginRequestObject) (PostLoginResponseObject, error)
	// ログアウト
	// (POST /logout)
	PostLogout(ctx context.Context, request PostLogoutRequestObject) (PostLogoutResponseObject, error)
	// ユーザー登録
	// (POST /register)
	PostRegister(ctx context.Context, request PostRegisterRequestObject) (PostRegisterResponseObject, error)
	// ユーザー詳細取得
	// (GET /users/{user_id})
	GetUsersUserId(ctx context.Context, request GetUsersUserIdRequestObject) (GetUsersUserIdResponseObject, error)
	// ユーザー情報編集
	// (PUT /users/{user_id})
	PutUsersUserId(ctx context.Context, request PutUsersUserIdRequestObject) (PutUsersUserIdResponseObject, error)
	// Todo一覧取得
	// (GET /users/{user_id}/todos)
	GetUsersUserIdTodos(ctx context.Context, request GetUsersUserIdTodosRequestObject) (GetUsersUserIdTodosResponseObject, error)
	// Todo作成
	// (POST /users/{user_id}/todos)
	PostUsersUserIdTodos(ctx context.Context, request PostUsersUserIdTodosRequestObject) (PostUsersUserIdTodosResponseObject, error)
	// Todo削除
	// (DELETE /users/{user_id}/todos/{todo_id})
	DeleteUsersUserIdTodosTodoId(ctx context.Context, request DeleteUsersUserIdTodosTodoIdRequestObject) (DeleteUsersUserIdTodosTodoIdResponseObject, error)
	// Todo詳細取得
	// (GET /users/{user_id}/todos/{todo_id})
	GetUsersUserIdTodosTodoId(ctx context.Context, request GetUsersUserIdTodosTodoIdRequestObject) (GetUsersUserIdTodosTodoIdResponseObject, error)
	// Todo編集
	// (PUT /users/{user_id}/todos/{todo_id})
	PutUsersUserIdTodosTodoId(ctx context.Context, request PutUsersUserIdTodosTodoIdRequestObject) (PutUsersUserIdTodosTodoIdResponseObject, error)
	// いいね削除
	// (DELETE /users/{user_id}/todos/{todo_id}/goodlucks)
	DeleteUsersUserIdTodosTodoIdGoodlucks(ctx context.Context, request DeleteUsersUserIdTodosTodoIdGoodlucksRequestObject) (DeleteUsersUserIdTodosTodoIdGoodlucksResponseObject, error)
	// いいね作成
	// (POST /users/{user_id}/todos/{todo_id}/goodlucks)
	PostUsersUserIdTodosTodoIdGoodlucks(ctx context.Context, request PostUsersUserIdTodosTodoIdGoodlucksRequestObject) (PostUsersUserIdTodosTodoIdGoodlucksResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// PostLogin operation middleware
func (sh *strictHandler) PostLogin(ctx *gin.Context) {
	var request PostLoginRequestObject

	var body PostLoginJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostLogin(ctx, request.(PostLoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostLogin")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostLoginResponseObject); ok {
		if err := validResponse.VisitPostLoginResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostLogout operation middleware
func (sh *strictHandler) PostLogout(ctx *gin.Context) {
	var request PostLogoutRequestObject

	var body PostLogoutJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostLogout(ctx, request.(PostLogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostLogout")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostLogoutResponseObject); ok {
		if err := validResponse.VisitPostLogoutResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostRegister operation middleware
func (sh *strictHandler) PostRegister(ctx *gin.Context) {
	var request PostRegisterRequestObject

	var body PostRegisterJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostRegister(ctx, request.(PostRegisterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostRegister")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostRegisterResponseObject); ok {
		if err := validResponse.VisitPostRegisterResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetUsersUserId operation middleware
func (sh *strictHandler) GetUsersUserId(ctx *gin.Context, userId UserId) {
	var request GetUsersUserIdRequestObject

	request.UserId = userId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetUsersUserId(ctx, request.(GetUsersUserIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUsersUserId")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetUsersUserIdResponseObject); ok {
		if err := validResponse.VisitGetUsersUserIdResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutUsersUserId operation middleware
func (sh *strictHandler) PutUsersUserId(ctx *gin.Context, userId UserId) {
	var request PutUsersUserIdRequestObject

	request.UserId = userId

	var body PutUsersUserIdJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PutUsersUserId(ctx, request.(PutUsersUserIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutUsersUserId")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PutUsersUserIdResponseObject); ok {
		if err := validResponse.VisitPutUsersUserIdResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetUsersUserIdTodos operation middleware
func (sh *strictHandler) GetUsersUserIdTodos(ctx *gin.Context, userId UserId) {
	var request GetUsersUserIdTodosRequestObject

	request.UserId = userId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetUsersUserIdTodos(ctx, request.(GetUsersUserIdTodosRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUsersUserIdTodos")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetUsersUserIdTodosResponseObject); ok {
		if err := validResponse.VisitGetUsersUserIdTodosResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostUsersUserIdTodos operation middleware
func (sh *strictHandler) PostUsersUserIdTodos(ctx *gin.Context, userId UserId) {
	var request PostUsersUserIdTodosRequestObject

	request.UserId = userId

	var body PostUsersUserIdTodosJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostUsersUserIdTodos(ctx, request.(PostUsersUserIdTodosRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostUsersUserIdTodos")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostUsersUserIdTodosResponseObject); ok {
		if err := validResponse.VisitPostUsersUserIdTodosResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteUsersUserIdTodosTodoId operation middleware
func (sh *strictHandler) DeleteUsersUserIdTodosTodoId(ctx *gin.Context, userId UserId, todoId TodoId) {
	var request DeleteUsersUserIdTodosTodoIdRequestObject

	request.UserId = userId
	request.TodoId = todoId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteUsersUserIdTodosTodoId(ctx, request.(DeleteUsersUserIdTodosTodoIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteUsersUserIdTodosTodoId")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(DeleteUsersUserIdTodosTodoIdResponseObject); ok {
		if err := validResponse.VisitDeleteUsersUserIdTodosTodoIdResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetUsersUserIdTodosTodoId operation middleware
func (sh *strictHandler) GetUsersUserIdTodosTodoId(ctx *gin.Context, userId UserId, todoId TodoId) {
	var request GetUsersUserIdTodosTodoIdRequestObject

	request.UserId = userId
	request.TodoId = todoId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetUsersUserIdTodosTodoId(ctx, request.(GetUsersUserIdTodosTodoIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUsersUserIdTodosTodoId")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetUsersUserIdTodosTodoIdResponseObject); ok {
		if err := validResponse.VisitGetUsersUserIdTodosTodoIdResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutUsersUserIdTodosTodoId operation middleware
func (sh *strictHandler) PutUsersUserIdTodosTodoId(ctx *gin.Context, userId UserId, todoId TodoId) {
	var request PutUsersUserIdTodosTodoIdRequestObject

	request.UserId = userId
	request.TodoId = todoId

	var body PutUsersUserIdTodosTodoIdJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PutUsersUserIdTodosTodoId(ctx, request.(PutUsersUserIdTodosTodoIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutUsersUserIdTodosTodoId")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PutUsersUserIdTodosTodoIdResponseObject); ok {
		if err := validResponse.VisitPutUsersUserIdTodosTodoIdResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteUsersUserIdTodosTodoIdGoodlucks operation middleware
func (sh *strictHandler) DeleteUsersUserIdTodosTodoIdGoodlucks(ctx *gin.Context, userId UserId, todoId TodoId) {
	var request DeleteUsersUserIdTodosTodoIdGoodlucksRequestObject

	request.UserId = userId
	request.TodoId = todoId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteUsersUserIdTodosTodoIdGoodlucks(ctx, request.(DeleteUsersUserIdTodosTodoIdGoodlucksRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteUsersUserIdTodosTodoIdGoodlucks")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(DeleteUsersUserIdTodosTodoIdGoodlucksResponseObject); ok {
		if err := validResponse.VisitDeleteUsersUserIdTodosTodoIdGoodlucksResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostUsersUserIdTodosTodoIdGoodlucks operation middleware
func (sh *strictHandler) PostUsersUserIdTodosTodoIdGoodlucks(ctx *gin.Context, userId UserId, todoId TodoId) {
	var request PostUsersUserIdTodosTodoIdGoodlucksRequestObject

	request.UserId = userId
	request.TodoId = todoId

	var body PostUsersUserIdTodosTodoIdGoodlucksJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostUsersUserIdTodosTodoIdGoodlucks(ctx, request.(PostUsersUserIdTodosTodoIdGoodlucksRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostUsersUserIdTodosTodoIdGoodlucks")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostUsersUserIdTodosTodoIdGoodlucksResponseObject); ok {
		if err := validResponse.VisitPostUsersUserIdTodosTodoIdGoodlucksResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaX28TRxD/Kta2D610cA4JVXRvpRAEigBBIh4QQhvfxF7w3R67e4E0skRsilKKVJSH",
	"tqiVaBGipRUSLVX/COiXORLCt6h292yf7b2cnbMdSv0SOXvemd/+5rdzM7teQyXqBdQHX3DkrKEAM+yB",
	"AKb+E9Sll4grPxIfOSjAooIs5GMPkNN6aiEGV0PCwEWOYCFYiJcq4GE5bZkyDwvkoFIFsw+mP/oQWUis",
	"BnI6F4z4ZVSrWSjkwNL9NJ/27+fQrMlPTRrgAfU5qNUdwe5ZuBoCF/K/EvUF+OojDoIqKWFBqG9f5tSX",
	"Y21XcB17QRXUR8YoQw4i/gquErfAtLnCEnVXUc1CAaMBMEG0v/jbawYC4hG6dBlKQkN1gZcYCSQI5Eis",
	"hSbYmoXmKFsirgt+XuTLLUNDhTuXNHvCF8B8XD0HbAXYsabZfIRrkwWubBb0+FCX0ERd0LALx5ouTlEx",
	"R0PfzbsGn4rCsjI0VNynqCjMNc0u+jgUFcrIp5Abb5i0NVTIHSjlY41D2f2EARZwnFK3GpauJPZrp/tE",
	"puoj5XRknH5SR88irB5gOrH0IvOAc1yGvqhpWl2gLk1daiKGHr4+D35ZVJAzVSwWDet0Q7jkYgGCeNCx",
	"WDl4QI0aZnGBRcgN5Bi5FERopSTgTBct5BG/hc4adPFpdPYdY5ODo1CF4cdMW90d9mAWj4OQ5o6CwKSa",
	"bvTdVUJMwDzhIrl8IsDjvTzsbWkDZIt9YiEewIzh1ZiVRQ4sSxbgYVLtAKtHDFB9Urqiq6y+dDlPy8SX",
	"EFKT0wC+A8z5Nco6o9AatJLsHepkb9YaEGwaU7hUAs4vCXpFV1ItGJevCRNkBssMeKX/CWGuV8w8LdNQ",
	"7Mp3/vdY0slwstdZKBMugA1LKEmRJvPc4YwtNXqJda70P6qyxcD9/5YcycWPpOTQDvZ7K2QhG/erRAYc",
	"SiEjYvWcrPW1tyXADFj701zT6cnzC6i7aTh5fqGwIHdI4eNQVMAXcTOD4vZBuosNttxXhAh0A0L8ZapK",
	"hw6bUf1BVP8lqj+KGs+ixsbre8/f3Plt+/H9ncbLaP3Oq+ffROs3o/X7C6ePno4aP0f1v6PGRlTffPXy",
	"u6j+RXSjjlrKRGV6oEz8A9dgCQcEWWgFGNdOpg4WDxYlYzQAXz500LQastS5h2LCrsqXl4oH1ZLpAtp4",
	"EtWfRvWHEmh9c+eHO9H6LQ1Ahk8RccJFDjpDuVAvwvj0BLg4Qt3VgXrB9xksIwe9Z7ePiuy4Q7N7KoL4",
	"mCV5TtN97nKoWByF/1jDhv4yydb2xt2t2/cl/TMahsl6C66dOCOqWehwP1NMxx1K8KHnYbbahUc9kuGm",
	"ociO9wOlzY1+Qi7tjSzmXWXJ+IPeXbLsEvWYs1yBnylOZU9Z7DogyaeWOD0i50I7MV64WLtoElK8RK0l",
	"Fhclu6npUdR4EdX/iBovdI7LFFSz0hmRpEwl45hFZazljLLqJu/tSCndqLQYZH/A7bW4TahJV2XIkMTO",
	"42evf38a1Te3vvxq65+vo/V7rbdbpzDifpTLPydc9f5q3x5cMC+q/RW72btITY8srOaeOSOumgG9/PHn",
	"jZnidPakjhP2meJM9ozWufWYUpOZTtWWhRkK3G58tvX9r1F98/WfP7359la6As+EQ1Tg8NNab/E/5qRm",
	"qPEzpK+p17xPpJ9b+kk6jRnZFtSlPDUvy8701V83dh79OHA+XlCG39ak3HO8a9Ble/GTVJxDj900qhRs",
	"LAzlN3U/u71xd5esS/mwhTb83Nt7kzbm3Gu4zUrTuOJ7ou69q1sRuEt+tdfiC+KaFn0VBKTKf+vz22/u",
	"PUyXv77v694A8k+eEsTK/GrzjnukqdlwmZmiWk3TRLV7Vq0mUPpLffXvsRV7lwRpvgtP0eSkcRuKMvtq",
	"2OJsOViLti/KHFVjt4/FheHeKmVLTFq5nJshs3lrFxd2Of5pEd+tzFCXSDej9Sc5a43jLWfvRtHR87ss",
	"01FFk7tJ9ZHnhKKTxfSGMCnVvXSF+ybUUfWT3T9E3ZeecqCNMmkuh7FRWh2mmiktaf2GrBr/rsCx7Sot",
	"4WqFcuHMFmeLNg6IvTKFahdr/wYAAP//lRFUu2YxAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
